meta_product_name: "Telewise"
meta_title: "Telewise - Never miss an episode again"
meta_description: "Keep track of your favourite shows with Telewise."
meta_image: "cover.png" # should exist in `app/assets/images/`
